### ISSUE TITLE
Add ```label_list``` options to ```preprocess.py```

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/SEC-DOC-TAGGING#1]
Currently, we generate and filter the label_list in ```preprocess.py```. We should generate the list and parse it externally, then pass the label_list to ```preprocess.py``` for actual data filtering.

**Comment by kamilkrukowski** [comment]
Let's use python argparser so we can do something of the following form:
```python preprocess.py --labels labels.txt``` and it would use a ```labels.txt``` local file instead.
If the optional command line argument is not provided, we can default to an internal exhaustive label list.
```python preprocess.py``` would generate and use a default ```labels.txt``` internally if an external one is not provided

**Comment by kamilkrukowski** [comment]
Does this make sense @yyitingli ?

We should start a ```generate_labels.py``` auxiliary helper script that can use some hyper parameters + manual changes on label list which we can feed into ```preprocess.py```

**Comment by yyitingli** [comment]
The final output is two file:
1. generate_labels.py - generate label.txt (can be modified using hyper parameters)
2. preprocess.py -  add argparser to use the local label.txt file.  No option => create label list

**Comment by kamilkrukowski** [comment]
Yes! With a local label.txt option in the working directory we can manually modify it as we wish.

Remember, we'd like the ```-nonnumeric``` option from ```preprocess.py``` to be available in ```generate_labels.py```

Please consider rebasing from recent changes.
