### ISSUE TITLE
Separate ```ix:numeric``` and ```ix:non-numeric``` label sets

### ISSUE THREAD

**Issue by kamilkrukowski** [kamilkrukowski/SEC-DOC-TAGGING#2]
We need to consider numeric and non-numeric labels separately in ```preprocess.py```

**Comment by yyitingli** [comment]
- add hyper parameter '-nonnumeric'

- drop all tags that are not nonnumeric

**Comment by kamilkrukowski** [comment]
If you could link the pull request to this issue, that would be great. Let's keep 1 branch = 1 issue = 1 pull request
